fix for 500 error if API returns 404
Real-Dev-Squad/members-site pull request #106
Opened 2023-11-11 10:20 UTC by vinayak-trivedi

2023-11-13 19:28 UTC, anishpawaskar reviewed
Double quotes are changed to double quotes, can you please change it back to single quotes. Other than that everything LGTM

2023-11-14 01:12 UTC, heyrandhir requested changes
Please use the PR description template provided by Tejas for the pull request.

2023-11-17 04:05 UTC, anishpawaskar approved these changes

2023-11-17 07:30 UTC, heyrandhir approved these changes

2023-11-18 14:19 UTC, merged