feat: add useAxios hook and tests
Real-Dev-Squad/members-site pull request #13
Opened 2023-01-14 07:30 UTC by archit7448

### Issue 
- Write useAxios hook and  tests for it.

### Files  to change
- ```jest.config.js```  for test setup
-  ```package.json```
      - Update react and react-testing-library version 
      - Add msw and axios
      - Inside scripts add test-coverage command.
- ```src/custom-hooks/useFetch.js```  change URL methods of passing change with props.

### Files to add 
- ```setupTests.ts```  add teardown
- ```mocks/server.ts``` add server
- ```mocks/handler.ts``` add handler
-  ```hooks/useAxios.ts``` feat: useFetch hook.
- ```__tests__/useAxios.ts``` test for useFetch hook.
  
 ### UseAxios hook 

 - The `useAxios` hook is a custom React hook for making HTTP requests with the `axios` library. It returns an object with three properties: `data`, `loading`, and `error`. The `data` property contains the response data, the `loading` property is a boolean that indicates whether the request is in progress, and the `error` property contains any error that occurred during the request.
 - The hook accepts a URL, an HTTP method (defaults to `GET`), and a configuration object that can be used to pass additional options to `axios`
 
### UseAxios hook test 

- The tests for the `useAxios` hook use the `msw` library to mock HTTP requests and verify that the hook returns the expected values for different scenarios, such as successful requests and failed requests.
- `get` , `patch` and `reject` request during testing.

2023-01-19 20:01 UTC, vvaibhavdesai requested changes

2023-01-19 20:01 UTC, vvaibhavdesai commented on src/__tests__/useAxios.ts
> +import { renderHook, waitFor } from "@testing-library/react";
can we sort the orders in the format of 
external library imports first 
then local library imports 
then local components and then at the last all the utilities

2023-01-29 13:10 UTC, Neha commented on src/__tests__/useAxios.ts
> +    const { result } = renderHook(() => useAxios("https://real-dev-squad.com"));
Move the URL to constant

2023-01-29 13:10 UTC, Neha commented on src/__tests__/useAxios.ts
> +        data: ["members-site", "real-dev", "real-dev-squad"],
Move the data to Constant

2023-01-29 13:10 UTC, Neha commented on src/__tests__/useAxios.ts
> +    const patchUrl = "https://real-dev-squad.com/endpoint";
Same as above...move to the constant

2023-01-29 13:12 UTC, Neha commented on src/hooks/useAxios.ts
> +  data: any;
we should not be using 'any'. Try to use unknown.

2023-01-29 13:14 UTC, Neha commented on src/hooks/useAxios.ts
> +  const [state, setState] = useState(intialState);
`useState< UseAxiosResult >`

2023-01-29 13:15 UTC, Neha commented on src/hooks/useAxios.ts
> +    cancelRequest.current = false;
what is current here mean?  If this is about status then rename this to status

2023-01-29 13:17 UTC, Neha reviewed
1. In test-cases, move all the hardcoded content to constant. 
2. Suggested a few rename and type suggestion.

2023-03-27 15:14 UTC, closed without merging