Dev to main sync PR
Real-Dev-Squad/members-site pull request #174
Opened 2024-09-13 17:08 UTC by ssxdev

Date: 

Developer Name: 

---

## Issue Ticket Number

## Description

### Documentation Updated?

- [ ] Yes
- [ ] No

### Under Feature Flag

- [ ] Yes
- [ ] No

### Database Changes

- [ ] Yes
- [ ] No

### Breaking Changes

- [ ] Yes
- [ ] No

### Development Tested?

- [ ] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

</details>

## Additional Notes

2024-09-14 07:17 UTC, Achintya-Chatterjee requested changes
first fill up all of the PR details

2024-09-16 07:49 UTC, Achintya-Chatterjee approved these changes

2024-09-16 19:38 UTC, Ayushsanjdev approved these changes

2024-09-17 17:55 UTC, iamitprakash approved these changes

2024-09-17 17:55 UTC, merged