feat: worked on member improvements
Real-Dev-Squad/members-site pull request #64
Opened 2023-07-24 17:09 UTC by vvaibhavdesai

- [ ]  made navbar sticky
- [ ] accordions open up based on the default behaviour 
- [ ] icons for members are added linking for those needs to be done

2023-07-25 09:40 UTC, anishpawaskar requested changes

2023-07-25 09:40 UTC, anishpawaskar commented on src/components/MemberProfileCard/index.tsx
> +  console.log(userData,"userData")
remove console

2023-07-25 09:40 UTC, anishpawaskar commented on src/components/Layout/Navbar/NavbarDesktop.tsx
>        sx={{
Please can you put this into module css

2023-07-25 14:46 UTC, vinayak-trivedi commented on src/components/MemberContribution/index.tsx
> +        fallBackLabel={"How is this person a member? 🤔"}
let's add these fallback labels in constants

2023-08-01 19:23 UTC, anishpawaskar approved these changes
LGTM

2023-08-02 05:43 UTC, vinayak-trivedi approved these changes
LGTM

2023-08-02 05:43 UTC, merged